name: Docker Image CI(test, build, deploy, and push docker image) to Docker Container registry/Docker Hub

env: 
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  building, testing, and push:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v3

    -name: login to docker hub/container
    -uses: docker/login-action@v4
     with:
       username: ${{env.DOCKER_USERNAME}}
       password: ${{env.DOCKER_PASSWORD}}
    
    -name: Test
     run:|
     echo --running test cases--
       docker run --rm
     echo --tests completed-- 
        
    -name: build and push docker image
    -uses: docker/build-push-action@v5
     with:
      context: .
      file: ./Dockerfile 
      push: true
      secrets: |
         token: ${{env.GIT_AUTH_TOKEN}}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
        echo --deploying to either vercel or docker repo--
        echo --done with deployment--
      
