name: Docker Image CI(test, build, deploy, and push docker image) to Docker Container registry/Docker Hub

env: 
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

on:
  push:
    branches: [ "master" ]
    path: ["Dockerfile", ".github/workflows/docker-image.yml"]
  pull_request:
    branches: [ "master" ]

jobs:

  building, testing, and push:

    runs-on: ubuntu-latest

    steps:
    - name: checkout master
    - uses: actions/checkout@v3

    - name: build and tag image
    - uses: docker/build-push-action@v4
      run: |
      docker build . \
      --tag $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION

    -name: login to docker hub/container
    -uses: docker/login-action@v4
      run: |
      docker login -u $DOCKER_USERNAME -p DOCKER_PASSWORD
    
        
    -name: Publishing the image to Dockerhub/registry
    -uses: docker/build-push-action@v5
      run: |
      docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$IMAGE_VERSION
     

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
        echo --deploying to either vercel or docker repo--
        echo --done with deployment--
      
