name: Docker Image CI(test, build, deploy, and push docker image)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  building and testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -name: Test
     run:|
       docker run --rm
       
    -name: build
      run: |
      docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      
