name: Docker Image CI(test, build, deploy, and push docker image)

env: 
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  building and testing:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
    - uses: actions/checkout@v3

    -name: login to docker hub/container
    -uses: docker/login-action@v3
     with:
        username: ${{env.DOCKER_USERNAME}}
        password: ${{env.DOCKER_PASSWORD}}
    
    -name: Test
     run:|
     echo --running test cases--
       docker run --rm
     echo --tests completed-- 
       
    -name: build
      run: |
      echo -- building the image--
      docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      echo -- done with building--

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
      echo --deploying to either vercel or docker repo--
      echo --done with deployment--
      
