name: CI(test, build, deploy, and push image) github container registry

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{github.repository}}      

jobs:

    build, test, and push:

        runs-on: ubuntu-latest
        
        permissions:
            contents: read
            packages: write

        steps:
        - name: checkout code
        - uses: actions/checkout@v3

        -name: login to container registry
        -uses: docker/login-action@v4
        with:
            registry: ${{env.REGISTRY}}
            username: ${{github.actor}}
            password: ${{secrets.GIT_AUTH_TOKEN}}

        -name: Extract metadata (tags, labels) for Docker
        -id: meta
        -uses: docker/metadata-action@9
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          
        -name: build and push docker image
        -uses: docker/build-push-action@v4
        with:
            context: .
            push: true  



